CFLAGS  = -g -Wall -I../../lab3/solutions_part1
LDFLAGS = -L../../lab3/solutions/part1
LDLIBS  = -lmylist
 
mdb-lookup-server: mdb-lookup-server.o

mdb-lookup-server: mdb-lookup-server.o 
 
mdb-lookup-server.o: mdb.h
 

.PHONY: clean
clean:
	rm -f *.o a.out mdb-lookup-server
